### ISSUE TITLE
java.lang.IndexOutOfBoundsException

### ISSUE THREAD

**Issue by Hipapheralkus** [augustd/burp-suite-software-version-checks#72]
Hi,
I'm running the newest and unchanged rules for this extender. It seems that at least one rule was put there with some mistake, because when I open Errors tab, I can see following: 
```
java.lang.IndexOutOfBoundsException: No group 2
	at java.util.regex.Matcher.group(Matcher.java:538)
	at com.codemagi.burp.PassiveScan.runPassiveScanChecks(PassiveScan.java:126)
	at burp.BurpExtender.processHttpMessage(BurpExtender.java:209)
	at burp.vec.run(Unknown Source)
	at java.lang.Thread.run(Thread.java:745)
java.lang.IndexOutOfBoundsException: No group 2
	at java.util.regex.Matcher.group(Matcher.java:538)
	at com.codemagi.burp.PassiveScan.runPassiveScanChecks(PassiveScan.java:126)
	at burp.BurpExtender.processHttpMessage(BurpExtender.java:209)
	at burp.vec.run(Unknown Source)
	at java.lang.Thread.run(Thread.java:745)
java.lang.IndexOutOfBoundsException: No group 2
	at java.util.regex.Matcher.group(Matcher.java:538)
	at com.codemagi.burp.PassiveScan.runPassiveScanChecks(PassiveScan.java:126)
	at burp.BurpExtender.processHttpMessage(BurpExtender.java:209)
	at burp.vec.run(Unknown Source)
	at java.lang.Thread.run(Thread.java:745)
java.lang.IndexOutOfBoundsException: No group 2
	at java.util.regex.Matcher.group(Matcher.java:538)
	at com.codemagi.burp.PassiveScan.runPassiveScanChecks(PassiveScan.java:126)
	at burp.BurpExtender.processHttpMessage(BurpExtender.java:209)
	at burp.vec.run(Unknown Source)
	at java.lang.Thread.run(Thread.java:745)
java.lang.IndexOutOfBoundsException: No group 2
	at java.util.regex.Matcher.group(Matcher.java:538)
	at com.codemagi.burp.PassiveScan.runPassiveScanChecks(PassiveScan.java:126)
	at burp.BurpExtender.processHttpMessage(BurpExtender.java:209)
	at burp.vec.run(Unknown Source)
	at java.lang.Thread.run(Thread.java:745)
java.lang.IndexOutOfBoundsException: No group 2
	at java.util.regex.Matcher.group(Matcher.java:538)
	at com.codemagi.burp.PassiveScan.runPassiveScanChecks(PassiveScan.java:126)
	at burp.BurpExtender.processHttpMessage(BurpExtender.java:209)
	at burp.vec.run(Unknown Source)
	at java.lang.Thread.run(Thread.java:745)
java.lang.IndexOutOfBoundsException: No group 2
	at java.util.regex.Matcher.group(Matcher.java:538)
	at com.codemagi.burp.PassiveScan.runPassiveScanChecks(PassiveScan.java:126)
	at burp.BurpExtender.processHttpMessage(BurpExtender.java:209)
	at burp.vec.run(Unknown Source)
	at java.lang.Thread.run(Thread.java:745)
java.lang.IndexOutOfBoundsException: No group 2
	at java.util.regex.Matcher.group(Matcher.java:538)
	at com.codemagi.burp.PassiveScan.runPassiveScanChecks(PassiveScan.java:126)
	at burp.BurpExtender.processHttpMessage(BurpExtender.java:209)
	at burp.vec.run(Unknown Source)
	at java.lang.Thread.run(Thread.java:745)
java.lang.IndexOutOfBoundsException: No group 2
	at java.util.regex.Matcher.group(Matcher.java:538)
	at com.codemagi.burp.PassiveScan.runPassiveScanChecks(PassiveScan.java:126)
	at com.codemagi.burp.PassiveScan.doPassiveScan(PassiveScan.java:105)
	at burp.dhd.run(Unknown Source)
	at java.lang.Thread.run(Thread.java:745)
java.lang.IndexOutOfBoundsException: No group 2
	at java.util.regex.Matcher.group(Matcher.java:538)
	at com.codemagi.burp.PassiveScan.runPassiveScanChecks(PassiveScan.java:126)
	at com.codemagi.burp.PassiveScan.doPassiveScan(PassiveScan.java:105)
	at burp.dhd.run(Unknown Source)
	at java.lang.Thread.run(Thread.java:745)
java.lang.IndexOutOfBoundsException: No group 2
	at java.util.regex.Matcher.group(Matcher.java:538)
	at com.codemagi.burp.PassiveScan.runPassiveScanChecks(PassiveScan.java:126)
	at com.codemagi.burp.PassiveScan.doPassiveScan(PassiveScan.java:105)
	at burp.dhd.run(Unknown Source)
	at java.lang.Thread.run(Thread.java:745)

```

**Comment by augustd** [comment]
Thanks, I will look into this ASAP.

**Comment by augustd** [comment]
@Hipapheralkus this can happen when there is a partial match of one of the detection patterns. It might indicate a false positive or a software that has changed its version header. 

Can you please send me an example of one of the responses where you got this Exception (at least the version part)?
